import Image from "next/image";
import Link from "next/link";
import { Breadcrumb } from "@/components/breadcrumb";
import { FAQ } from "@/components/faq";
import { JsonLd } from "@/components/json-ld";
import { ButtonLink, Eyebrow, Section } from "@/components/ui";
import type { Guide } from "@/data/site";
import { articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/lib/jsonld";

const ratSigns = ["bruits de déplacement ou grattements assez marqués ;", "traces de rongement importantes ;", "passages répétés le long des murs ;", "présence possible dans les caves, garages, locaux techniques, jardins ou zones proches des déchets ;", "odeur persistante dans une zone confinée."];
const mouseSigns = ["petits bruits rapides, notamment la nuit ;", "emballages alimentaires grignotés ;", "petits rongements sur du carton, du plastique ou certains câbles ;", "présence dans les placards, cuisines, réserves, faux plafonds ou derrière les meubles ;", "petits matériaux déchiquetés pouvant servir à former un nid."];

export function RodentDroppingsGuidePage({ guide, crumbs }: { guide: Guide; crumbs: Array<{ name: string; href: string }> }) {
  return <main className="overflow-x-hidden">
    <JsonLd data={[breadcrumbJsonLd(crumbs), faqJsonLd(guide.faq), articleJsonLd(guide.title, guide.description, `/guides/${guide.slug}/`, guide.published)]} />
    <Breadcrumb items={crumbs} />
    <Section className="py-10 sm:py-16"><div className="container max-w-[1100px]"><Eyebrow>GUIDE D&apos;IDENTIFICATION DES RONGEURS</Eyebrow><h1 className="max-w-4xl text-4xl font-black leading-tight text-[#102337] sm:text-5xl">Crottes de rat ou de souris : comment les reconnaître ?</h1><div className="mt-6 max-w-3xl space-y-4 text-lg leading-8 text-[#405160]"><p>Vous avez trouvé de petites crottes noires dans une cuisine, un garage, des combles ou derrière un meuble ? La taille et la forme des déjections peuvent donner un premier indice pour distinguer un rat d&apos;une souris.</p><p>Mais une crotte seule ne permet pas toujours d&apos;identifier le rongeur avec certitude. L&apos;emplacement, les bruits, les traces de passage et les dégâts observés doivent aussi être pris en compte.</p></div><p className="mt-7 max-w-4xl border-l-4 border-[#F2C94C] bg-white p-5 font-bold leading-7 text-[#102337]">En bref : les crottes de souris sont généralement petites, fines et proches de la forme d&apos;un grain de riz. Les déjections de rat sont habituellement plus grandes et plus épaisses. Ces repères restent indicatifs : plusieurs indices doivent être croisés avant de conclure.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/demande-devis/">Décrire mon problème</ButtonLink><ButtonLink href="/deratisation-var/" variant="secondary">Voir la dératisation dans le Var</ButtonLink></div></div></Section>
    <Section tone="white"><article className="container max-w-[1000px] [&>section+section]:border-t [&>section+section]:border-[#102337]/10 [&>section+section]:pt-14 sm:[&>section+section]:pt-16">
      <section><H2>Crottes de rat ou de souris : les différences à observer</H2><P>Le premier réflexe consiste souvent à regarder la taille des déjections. C&apos;est utile, mais il faut éviter de se fier à un seul critère.</P><P>Selon l&apos;espèce, l&apos;alimentation et l&apos;état des déjections, leur apparence peut varier. Utilisez donc les éléments suivants comme des repères d&apos;identification et non comme un diagnostic certain.</P><figure className="mt-8"><div className="overflow-x-auto overscroll-x-contain pb-2"><div className="min-w-[720px] sm:min-w-0"><Image src="/images/guides/crottes-rat-ou-souris.webp" alt="Illustration comparative des indices permettant de distinguer un rat d'une souris" width={1536} height={1024} sizes="(max-width: 640px) 720px, (max-width: 1100px) 92vw, 1000px" className="h-auto w-full border border-[#102337]/10" /></div></div><p className="mt-2 text-xs font-bold text-[#405160] sm:hidden">Faites glisser pour voir le comparatif.</p><figcaption className="mt-2 text-sm leading-6 text-[#405160]">Repères indicatifs : la taille et l&apos;apparence peuvent varier. Croisez toujours plusieurs signes de présence.</figcaption></figure><div className="mt-8 grid overflow-hidden border border-[#102337]/15 md:grid-cols-2"><Comparison title="Indices pouvant évoquer un rat" text="Les déjections attribuées aux rats sont généralement plus grandes et plus épaisses que celles des souris. Elles peuvent avoir une forme allongée, avec des extrémités plus ou moins arrondies ou effilées selon l'espèce." items={ratSigns}/><Comparison title="Indices pouvant évoquer une souris" text="Les crottes de souris sont généralement plus petites et plus fines. Leur forme est souvent comparée à celle d'un petit grain de riz sombre, parfois légèrement pointu à une extrémité." items={mouseSigns} second/></div><aside className="mt-6 border-l-4 border-[#1F4D3A] bg-[#F6F1E8] p-5"><h3 className="text-xl font-black text-[#102337]">À retenir</h3><P>Une différence nette de taille peut orienter l&apos;identification, mais ne concluez pas uniquement à partir d&apos;une déjection isolée. Regardez aussi où elle a été trouvée et recherchez d&apos;autres signes de présence.</P></aside></section>
      <section><H2>Où avez-vous trouvé les crottes ?</H2><P>L&apos;emplacement des déjections apporte souvent autant d&apos;informations que leur apparence.</P><div className="mt-6 divide-y divide-[#102337]/15 border-y border-[#102337]/15"><Place title="Dans la cuisine ou les placards">Des déjections près des aliments, dans un tiroir, sous un évier ou derrière un appareil électroménager peuvent indiquer le passage d&apos;un rongeur à la recherche de nourriture.<br/><br/>Regardez si des emballages ont été percés ou grignotés et si de nouvelles traces apparaissent.</Place><Place title="Dans les combles ou un faux plafond">Des bruits nocturnes, des matériaux déplacés et des traces dans l&apos;isolation peuvent renforcer la suspicion de présence de rongeurs.<br/><br/>Le bruit seul ne permet cependant pas de déterminer s&apos;il s&apos;agit d&apos;un rat ou d&apos;une souris.</Place><Place title="Dans un garage, une cave ou un local technique">Ces zones offrent parfois des passages discrets, des points d&apos;entrée et des endroits peu dérangés. Vérifiez les bas de murs, les angles, les zones de stockage et les abords des portes.</Place><Place title="Dans le jardin ou près des poubelles">La présence de nourriture accessible, de déchets ou d&apos;abris peut favoriser le passage de rats. Recherchez également des traces de circulation, des ouvertures ou des zones régulièrement fréquentées.</Place></div></section>
      <section><H2>Quels autres signes permettent de reconnaître un rat ou une souris ?</H2><P>Pour mieux identifier le problème, croisez l&apos;apparence des déjections avec plusieurs indices.</P><div className="mt-6 grid gap-x-8 gap-y-6 sm:grid-cols-2"><Sign title="Les bruits">Grattements, déplacements ou petits bruits dans les murs et plafonds sont souvent plus perceptibles lorsque le logement devient calme.</Sign><Sign title="Les rongements">Emballages, cartons, matériaux ou câbles endommagés peuvent révéler une activité de rongeurs.</Sign><Sign title="Les traces de passage">Des passages répétés le long d&apos;un mur peuvent laisser des marques ou rendre certains itinéraires plus visibles.</Sign><Sign title="Les matériaux de nidification">Papier, tissu, carton ou autres matériaux déchiquetés peuvent être utilisés pour aménager un abri.</Sign><Sign title="Les odeurs">Une odeur inhabituelle et persistante dans une zone peu ventilée peut accompagner une présence régulière de rongeurs.</Sign></div></section>
      <section><H2>Comment savoir si les crottes sont récentes ?</H2><P>L&apos;aspect des déjections peut évoluer avec le temps, mais il est difficile de dater précisément une crotte de rat ou de souris simplement en la regardant.</P><P>Plutôt que de chercher à déterminer un âge exact, observez si de nouvelles traces apparaissent après un nettoyage réalisé avec les précautions adaptées.</P><P>La répétition des déjections au même endroit, de nouveaux bruits ou des dégâts récents sont des signes plus utiles pour suspecter une activité en cours.</P><aside className="mt-6 border-2 border-[#E86A33] p-5"><h3 className="text-xl font-black text-[#102337]">Ne manipulez pas les déjections à mains nues</h3><P>Les déjections et les zones souillées par des rongeurs doivent être manipulées avec précaution. Évitez de les balayer ou de les aspirer à sec. Portez des gants et humidifiez la zone avec un produit désinfectant adapté avant de retirer les déjections avec un matériau jetable. Respectez les instructions du produit utilisé.</P></aside></section>
      <section><H2>J&apos;ai trouvé des crottes de rat ou de souris : que faire ?</H2><P>Trouver quelques déjections ne permet pas d&apos;évaluer à lui seul l&apos;importance du problème. L&apos;objectif est d&apos;abord de vérifier si d&apos;autres signes montrent une activité régulière.</P><ol className="mt-5 grid gap-3 pl-6 text-[#405160] [list-style:decimal]"><li>Repérez précisément les zones concernées.</li><li>Vérifiez les aliments et emballages accessibles.</li><li>Recherchez des trous, passages ou espaces autour des canalisations.</li><li>Notez les bruits et les moments où ils se produisent.</li><li>Observez si de nouvelles traces apparaissent.</li><li>Si le doute persiste ou si les signes se multiplient, décrivez la situation afin d&apos;orienter votre demande.</li></ol><div className="mt-8 bg-[#102337] p-6 text-white sm:p-8"><h3 className="text-2xl font-black">Rat ou souris ? Décrivez les signes observés</h3><p className="mt-3 max-w-2xl leading-7 text-white/80">Indiquez votre commune, le type de lieu et les indices repérés. Vous pouvez ajouter une photo si elle aide à comprendre la situation. L&apos;analyse reste indicative et ne remplace pas l&apos;avis d&apos;un professionnel.</p><div className="mt-5"><ButtonLink href="/demande-devis/">Ajouter une photo à ma demande</ButtonLink></div><p className="mt-4 text-sm text-white/70">Demande gratuite et sans engagement. Transmission à un professionnel partenaire uniquement avec votre consentement.</p></div></section>
      <section><H2>Pourquoi agir lorsque les signes se répètent ?</H2><P>Des déjections qui réapparaissent, des aliments endommagés ou des bruits réguliers peuvent indiquer qu&apos;un rongeur continue de circuler dans le bâtiment.</P><P>Les rats et les souris peuvent contaminer des surfaces et des denrées par leurs déjections ou leur urine. Leurs rongements peuvent également détériorer des emballages, des matériaux et parfois des câbles.</P><P>Lorsque plusieurs signes se cumulent, il est préférable de chercher l&apos;origine du passage et les points d&apos;accès plutôt que de simplement nettoyer les traces visibles.</P><p className="mt-4"><TextLink href="/deratisation-var/">solutions de dératisation dans le Var</TextLink></p></section>
      <section><H2>Besoin d&apos;identifier un autre nuisible ?</H2><P>Les traces trouvées dans un logement ne proviennent pas toujours d&apos;un rat ou d&apos;une souris. Insectes, autres animaux ou simples salissures peuvent parfois prêter à confusion.</P><P>Si les indices observés ne correspondent pas aux repères de cette page, consultez notre guide général pour comparer les principaux nuisibles rencontrés dans le Var.</P><p className="mt-4"><TextLink href="/guides/identifier-un-nuisible-var/">Identifier un nuisible dans le Var</TextLink></p></section>
      <section><H2>Questions fréquentes sur les crottes de rat et de souris</H2><div className="mt-6"><FAQ items={guide.faq}/></div></section>
    </article></Section>
  </main>;
}
function H2({children}:{children:React.ReactNode}) { return <h2 className="text-3xl font-black leading-tight text-[#102337]">{children}</h2>; }
function P({children}:{children:React.ReactNode}) { return <p className="mt-4 leading-8 text-[#405160]">{children}</p>; }
function Comparison({title,text,items,second=false}:{title:string;text:string;items:string[];second?:boolean}) { return <div className={`p-6 ${second ? "border-t border-[#102337]/15 bg-[#F6F1E8] md:border-l md:border-t-0" : "bg-white"}`}><h3 className="text-2xl font-black text-[#102337]">{title}</h3><P>{text}</P><p className="mt-5 font-bold text-[#102337]">Autres indices à observer :</p><ul className="mt-3 grid gap-2 pl-5 leading-7 text-[#405160] [list-style:disc]">{items.map(x=><li key={x}>{x}</li>)}</ul></div>; }
function Place({title,children}:{title:string;children:React.ReactNode}) { return <div className="grid gap-3 py-5 sm:grid-cols-[260px_1fr]"><h3 className="text-xl font-black text-[#102337]">{title}</h3><p className="leading-7 text-[#405160]">{children}</p></div>; }
function Sign({title,children}:{title:string;children:React.ReactNode}) { return <div className="border-l-2 border-[#1F4D3A] pl-4"><h3 className="font-black text-[#102337]">{title}</h3><p className="mt-2 leading-7 text-[#405160]">{children}</p></div>; }
function TextLink({href,children}:{href:string;children:React.ReactNode}) { return <Link className="focus-ring font-black text-[#a6422b] underline decoration-2 underline-offset-4 transition hover:text-[#7f2f1e]" href={href}>{children}</Link>; }
